---
kind: pipeline
type: docker
name: gravity-gateway-tests

trigger:
  branch:
    - main
    - add-drone

steps:
- name: publish-image
  image: plugins/docker
  dockerfile: ./Dockerfile
  context: .
  repo: gravityhuborg/gateway-tests
  tags: "${DRONE_BRANCH}"
  secrets: [docker_username,docker_password]

- name: test-waves
  image: gravityhuborg/gateway-tests:$DRONE_BRANCH
  commands:
  - make waves

- name: test-eth
  image: gravityhuborg/gateway-tests:$DRONE_BRANCH
  commands:
  - make ethereum
