kind: pipeline
type: docker
name: gravity-data-extractor

trigger:
  branch:
    - master
    - price-version

pipeline:
  publish-data-extractor:
    image: plugins/docker
    dockerfile: ./Dockerfile
    context: .
    repo: gravityhuborg/gateway-tests
    tags: [latest,"${DRONE_BRANCH}"]
    secrets: [docker_username,docker_password]

  test-waves:
    image: gravityhuborg/gateway-tests:$DRONE_BRANCH
    commands:
    - make waves

  test-eth:
    image: gravityhuborg/gateway-tests:$DRONE_BRANCH
    commands:
    - make ethereum
